Repository kubevirt/cloud-provider-kubevirt, pull requests merged in 2022-07, with the labels that each got.

#88 Add a possibility to read namespace from CCM config
  pkg/provider/cloud.go
  pkg/provider/cloud_test.go
Labels: size/S, dco-signoff: yes, lgtm, approved, ok-to-test

#96 infra: Add a gh actions to publish images
  .github/workflows/publish.yaml
Labels: size/M, dco-signoff: yes, lgtm, approved

#98 make: Disable CGO
  Makefile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#99 InstancesV2: Add option to disable getting Region and Zone labels
  pkg/provider/cloud.go
  pkg/provider/cloud_test.go
  pkg/provider/instances_v2.go
  pkg/provider/instances_v2_test.go
Labels: size/L, dco-signoff: yes, lgtm, approved, ok-to-test

#101 Change Dockerfile base images
  build/images/kubevirt-cloud-controller-manager/Dockerfile
Labels: size/S, dco-signoff: yes, lgtm, approved

#111 Use public registry for ubi9/ubi-micro base image
  build/images/kubevirt-cloud-controller-manager/Dockerfile
Labels: size/XS, dco-signoff: yes, lgtm, approved

#110 container: Storage golang deps at different layer
  Makefile
  build/images/kubevirt-cloud-controller-manager/Dockerfile
Labels: size/S, dco-signoff: yes, lgtm, approved

#100 infra: Add kubevirtci cluster infrastructure
  .gitignore
  Makefile
  cluster/addons/rbac/cloud-controller-manager-role-bindings.yaml
  cluster/addons/rbac/cloud-controller-manager-roles.yaml
  cluster/manifests/kubevirt-cloud-controller-manager-deploy.yaml
  cluster/manifests/kubevirt-cloud-controller-manager-pod.yaml
  config/default/kustomization.yaml
  config/kubevirtci/kustomization.yaml
  config/kubevirtci/manager_image_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/kccm_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/service_account.yaml
  config/secret/cloud-config
  config/secret/kustomization.yaml
  hack/functest.sh
  kubevirtci
Labels: size/XL, dco-signoff: yes, lgtm, approved

#108 verification: Integrate golangci-lint
  .golangci.yml
  Makefile
  cmd/kubevirt-cloud-controller-manager/main.go
  pkg/provider/cloud.go
  pkg/provider/cloud_test.go
  pkg/provider/loadbalancer.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#115 Adding Radim and Quique to OWNERS file
  OWNERS
Labels: size/XS, dco-signoff: yes, lgtm, approved

#113 Wait for components deployed in kubevirtci::prepare
  kubevirtci
Labels: size/M, dco-signoff: yes, lgtm, approved

#114 Unify indenting in kubevirtci to use tabs
  kubevirtci
Labels: size/L, dco-signoff: yes, lgtm, approved

#116 infra: Add github release action
  .github/workflows/publish.yaml
Labels: size/S, dco-signoff: yes, lgtm, approved

#119 actions, release: Push a tarball with config
  .github/workflows/publish.yaml
Labels: size/XS, dco-signoff: yes

#120 actions, release: Fix tarball generation
  .github/workflows/publish.yaml
Labels: dco-signoff: yes

#109 Introduce e2e suite
  Makefile
  go.mod
  hack/build-e2e.sh
  hack/functest.sh
  hack/run-e2e.sh
  test/e2e/cloud_provider_kubevirt/cloud_provider_kubevirt_suite_test.go
  test/e2e/cloud_provider_kubevirt/load_balancer_test.go
  test/e2e/naming/namespace.go
  test/e2e/resource/operations.go
  test/environment/environment.go
  test/resources/job.go
  test/resources/server.go
  test/testclient/testclient.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#125 kubevirtci: Deploy at tenant namespace
  config/configmap/kustomization.yaml
  config/default/kustomization.yaml
  config/kubevirtci/kustomization.yaml
  config/kubevirtci/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/ext_apiserver_auth_role_binding.yaml
  config/rbac/kccm_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/service_account.yaml
  config/secret/kustomization.yaml
  kubevirtci
Labels: size/M, dco-signoff: yes, lgtm, approved
