Repository kubevirt/cloud-provider-kubevirt, pull requests merged in 2022-09, with the labels that each got.

#143 Load balancer selector changes
  README.md
  pkg/provider/instances_v2.go
  pkg/provider/loadbalancer.go
  pkg/provider/loadbalancer_test.go
  test/e2e/cloud_provider_kubevirt/load_balancer_test.go
Labels: size/XXL, dco-signoff: yes, lgtm, approved

#141 kustomize: Add isolated overlay
  .gitignore
  config/base/kustomization.yaml
  config/base/manager_tenant_kubeconfig_secret_patch.yaml
  config/kubevirtci/kustomization.yaml
  config/kubevirtci/manager_tenant_kubeconfig_secret_patch.yaml
  config/overlays/default/cloud-config
  config/overlays/default/kustomization.yaml
  config/overlays/isolated/cloud-config
  config/overlays/isolated/kustomization.yaml
  config/overlays/kubevirtci/kustomization.yaml
  config/overlays/kubevirtci/manager_image_patch.yaml
  config/secret/kustomization.yaml
  hack/run-e2e.sh
  kubevirtci
  test/e2e/cloud_provider_kubevirt/cloud_provider_kubevirt_suite_test.go
Labels: size/L, dco-signoff: yes, lgtm, approved

#145 kustomize: Remove generated secret/cm suffix
  config/base/kustomization.yaml
  config/overlays/default/kustomization.yaml
  config/overlays/isolated/kustomization.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#146 kustomize: Create different base per overlay
  config/base/kustomization.yaml
  config/default/cloud-config
  config/default/kustomization.yaml
  config/isolated/cloud-config
  config/isolated/kustomization.yaml
  config/manager/manager.yaml
  config/overlays/default/kustomization.yaml
  config/overlays/isolated/kustomization.yaml
  config/overlays/kubevirtci/kustomization.yaml
Labels: size/L, dco-signoff: yes, lgtm, approved

#147 kustomize: Fix isolated overlay instancesV2 typo
  config/isolated/cloud-config
Labels: size/XS, dco-signoff: yes, lgtm, approved

#155 kustomize: Remove ref to kube-system isolated RBAC
  config/isolated/kustomization.yaml
Labels: size/XS, dco-signoff: yes, lgtm, approved

#157 test, e2e: Add k8s reporter from kubevirt
  .gitignore
  hack/run-e2e.sh
  test/e2e/cloud_provider_kubevirt/cloud_provider_kubevirt_suite_test.go
Labels: size/M, dco-signoff: yes, lgtm, approved

#156 kustomize, isolated: Remove nodes RBAC
  config/isolated/kustomization.yaml
  config/rbac/kccm_role.yaml
Labels: size/S, dco-signoff: yes, lgtm, approved

#142 rewrite unit-tests with ginkgo
  pkg/provider/loadbalancer_test.go
Labels: size/XXL, dco-signoff: yes, lgtm, approved, ok-to-test
